#ifndef INDICES_GLSL
#define INDICES_GLSL

const int DEPTH_SSBO_BINDING = 0;
const int CASCADE_SSBO_BINDING = 1;

const int B_SHADOW_CASCADE_DEPTH_ADJUST_LOCATION = 100;
const int B_SHADOW_TEXEL_MOVE_LOCATION = 101;

const int Z_PARTITION_COMP_SHADOW_MAP_RES_LOCATION = 0;
const int Z_PARTITION_COMP_CAMERA_NEAR_PLANE_LOCATION = 3;
const int Z_PARTITION_COMP_CAMERA_FAR_PLANE_LOCATION = 4;
const int Z_PARTITION_COMP_PROJ_VIEW_INV_LOCATION = 5;
const int Z_PARTITION_COMP_LIGHT_VIEW_LOCATION = 10;

const int LIGHTING_VERT_PROJ_VIEW_MODEL_LOCATION = 0;
const int LIGHTING_VERT_MODEL_LOCATION = 1;
const int LIGHTING_VERT_NORMAL_LOCATION = 2;

const int LIGHTING_FRAG_LIGHT_SHINE_DIR_LOCATION = 20;
const int LIGHTING_FRAG_CAMERA_POS_LOCATION = 40;
const int LIGHTING_FRAG_SHADOW_MAP_ARR_BINDING = 0;

const int SHADOW_VERT_TRANSFORM_LOCATION = 0;

#endif  // INDICES_GLSL
